### ISSUE TITLE
Expanding Test Suite

### ISSUE THREAD

**Issue by Speiger** [Speiger/Primitive-Collections#15]
Right now I am using Guavas Test-suite to ensure the quality of Primitive Collections.
But that right now only covers Javas Collection functions and only generics.
While Generics delegate to primitives, this isn't perfect either.
Since we have 7 implementations and a lot of custom functions, that means we don't have the coverage that I would like.

The end goal would be to have a Library like guavas Test-suite but for primitive collections.
Where a lot of features are supported and adding to that would be a lot easier.
This will most likely be its own library with maybe a dependency on Primitive Collections.

How would we get there is now the question.

Fairly easily actually. 
Since Guava provides a lot of the base that we actually want, we can start with it.
Then we just append our features on top of that.
Because we want to keep the Java Class Type to primitive type checks anyways that would ensure a Dual Check System.

Now since that still is a lot of work this isn't going to be completed anytime soon.
But it is here and it allows me to document progress properly.

So lets throw in a todo-list of what needs to be done.

- [x] Design a Framework that runs on top of Guavas Test Suite or makes use of it.
- [x] Write the designed Framework
   - [x] Collections
   - [x] Collections Template
   - [x] Lists
   - [x] Lists Template
   - [x] Sets
   - [x] Sets Template
   - [x] Queues
   - [x] Queues Template
   - [x] Maps
   - [x] Maps Template
   - [x] Extras
   - [x] Extras Template

If anyone wants to help with this you are welcome to do so.
Even with providing inputs or Sources how to improve this even more.

**Comment by Speiger** [comment]
Small Progress Update for anyone who is following.

I started implementing a whole UnitTest System that is testing as much as possible.
it is cloning a lot from guava and implementing primitive Variants.

Now that the Lists/Sets/Collections are implemented means I can now start writing templates for them.
Once these templates are written I can basically have for each implementation their own dedicated UnitTest.
Though the Object implementation isn't thought out yet.

Same with Maps.
But overall this is a good but slow process.
Without Maps this will get into the 50-70k unit tests which should improve the coverage a lot.

**Comment by Speiger** [comment]
Small Progress Update
The Improvements on code coverage are actually less then I expected. The Areas that are now covered were from 0 to +50% covered. A bit less then I expected. I was hoping for 80% but eh you can't have everything and it is only the start.

But I think the 0.6.2 version should be soon published since there were actual bugs found with the system and I was able to fix them thanks to this coverage.

**Comment by Speiger** [comment]
So after finally adding the Map unit Tests its time for a bit of recap.

I added Roughly 7 Million Unit tests to Primitive Collections with the Map Tests.
Which move the Coverage from 4.73% to 34.76% Coverage. Which is still below the Amount I am wishing for.
But I can't finish everything in a bulk process. This was so much work that I need to take a break from it.

But before I do I am going to make a new version since there were a lot of issues fixed.

Oh yeah by the way everything that is tested is at 40-50% coverage on average. Though there is exceptions in either direction.

**Comment by Speiger** [comment]
Coverage Tracker
[![codecov](https://codecov.io/gh/Speiger/Primitive-Collections/branch/debug/graph/badge.svg?token=WSTSNJM0EN)](https://codecov.io/gh/Speiger/Primitive-Collections)

**Comment by Speiger** [comment]
So I couldn't stop myself.
I added a couple more unit tests. Just like 100 or 200 and they resulted with a couple new implementations being added into 55.26% coverage. So we reached half way point in the testing department.

So it is growing.

**Comment by Speiger** [comment]
A bit more work done.
I added Support for the CollectionWrappers (SynchronizedX, UnmodifiableX, EmptyX, SingletonX) and that added a bit more coverage. Its not as much as the last one but we are now 62.94% Coverage.

The goal is 70-80%. Over time that might increase but the average should be around that.

**Comment by Speiger** [comment]
Another day another increase in Coverage.
We have reached 71.16% Coverage. Which is within the goals range but there is some things I still want to do.
Queues are not tested yet but that comes when i am done with maps.

Thanks to Guavas Test Library I was able to get a really good coverage.

**Comment by Speiger** [comment]
Well a bit more work done.
With the help of maps we are now at 80% coverage and 70% branch coverage (basically if all if statements are tested)
Which is the goal I had, but there is a bit more to do.
Sets/Lists are on average by 60% coverage, which is not the amount I want, and Queues aren't tested at all yet.
So the next thing I am going to work on is the Set/List implementation to get them up to 80% coverage at the very least too.
And that should also increase Map coverage a tiny bit too since there is a lot of tests that "sets" do that are included in "maps" too.

**Comment by Speiger** [comment]
Also since @@ben-manes was interested in notifications if I do some more.
To give you a small overview on what i did:
Basically I templated Guavas TestUnits and Created Primitive Variants on them (Generated automatically) and increased the test suite insanely.

(Not done yet though)

**Comment by ben-manes** [comment]
Congrats, you beat Caffeine's test suite size which is a mere 8.9 million. 😉 

I know you can extend Guava's testing framework to plug in more scenarios. It sounds like that is what you did?

For mine, I used TestNG's parameterized tests (`@DataProvider`), which generates the permutations from an method annotation (`@CacheSpec`), and passes in the instance to test and a context object describing the scenario (as sometimes needed by the test logic). Not externally reusable but very nice for my own needs.

**Comment by Speiger** [comment]
> I know you can extend Guava's testing framework to plug in more scenarios. It sounds like that is what you did?

Yep after looking into the options this was just very smooth to use.
While it is nice to use I am telling you it is not perfect solution either. It has some growing pains. Especially with "BooleanSets/Maps"

> Congrats, you beat Caffeine's test suite size which is a mere 8.9 million. 😉

😆 I am honest here. That wasn't even the plan. But thank you.

> For mine, I used TestNG's parameterized tests (@DataProvider), which generates the permutations from an method annotation (@CacheSpec), and passes in the instance to test and a context object describing the scenario (as sometimes needed by the test logic). Not externally reusable but very nice for my own needs.

That is also a fine way to do it. But sadly not applicable for the coverage I was aiming for. (I wanted to do tests for all permutations and have a very little impact on my templating process)


But believe me reaching the 80% wasn't easy... AT ALL....
![image](https://user-images.githubusercontent.com/2556269/172515349-4cf26a01-919b-4cf2-a25b-f0d2ddd4082b.png)

Complexity Coverage basically is "Branch Coverage" and as you can see the moment the tests were effectively applied that went up crazily xD

**Comment by Speiger** [comment]
And to update further notice to anyone reading this kinda semi blog.
Coverage is now at 83% average, where the average is slowly balancing to 85% and other packages slowly getting there too.
Queues still weren't started since the Lists/Sets aren't finished yet. Maps can only be completed by actually deleting duplicated code.

Misc is basically a wildcard that means anything that doesn't fit.

**Comment by Speiger** [comment]
Ok Reached 85% coverage, with each implementation of collections having a average coverage of 80-100% for each implementation. (Though queues are 60% average, but 90% of that is constructors)

But at this point I have to stop. I have been working on this for roughly 3 weeks now and need to stop and work on other projects.

Further tests come as I work on this project but a 85% coverage is healthy enough and makes sure everything works!

Some stats:
Primitive Collections on its debug branch has 11.382.503 Tests (11.3 Million Tests)
Which give it a coverage of 85.27% and a branch Coverage of 75.17%.
For everyone who just reads this comments: Branch Coverage is basically how many ifs are fully checked.

Out of 661.688 (662k) lines. (~81k per type)
564198 (564k) lines are fully tested. (~70k per type)
34943 (35k) are partially tested. (~4.2k per type)
62547 (63k) are not tested at all. (~7.2k per type)

So this is a huge project and now we have the stability and insurance everything is backed by unit tests.

I can only say if you are crazy enough to do something this large. Make sure you use templates. Otherwise you are crazy.

**Comment by Speiger** [comment]
Anyhow now pushing out the 0.7.0 update since this is not a patch anymore.

**Comment by Speiger** [comment]
And update 0.7.0 is out.
I have to thank you again @ben-manes. If you didn't suggest the Guava Test Lib to @vigna then I would never have started this and reach a coverage that should ensure the quality I wanted to have for my competing library.

@vigna you are free to look into the debug branch and try to improve the quality of FastUtils stability too if you want to.
To be fair, thank you for basically ignoring my want to improve the library, because this actually helped me to get a lot more invested in this kind of stuff and grow also as a coder but also as a person.

So thank you very much for that.
