### ISSUE TITLE
boolean-value maps (Int2BooleanMap) don't keep track of false values

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [Speiger/Primitive-Collections#28]
```java
Int2BooleanMap map = new Int2BooleanOpenHashMap();
map.computeBooleanIfAbsent(54, k -> false);
map.containsKey(54); // This should be true, but it returns false
```

**Comment by Speiger** [comment]
@KrystilizeNevaDies after careful consideration I decided not to change the behavior of the compute methods.
The "computeIfAbsent" function actually can be also viewed as "putIfAbsent" method.
> If the specified key is not already associated with a value (or is mapped to null), attempts to compute its value using the given mapping function and enters it into this map unless null.

https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfAbsent-K-java.util.function.Function-

Or in simplified terms (also based on javas implementation): The returned value will be inserted unless it is "null".
In the case the result of "getDefaultReturnValue()" defines what is "null" is and i try to be as consistent with that as possible.

I think in this case a dedicated method like for example: "insertIfAbsent" (for primitive values only) makes a lot more sense.

**Comment by Speiger** [comment]
@KrystilizeNevaDies updated info

**Comment by Speiger** [comment]
@KrystilizeNevaDies started changing methods. It will take a while but i am working on it :)
