### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by dfa1** [Speiger/Primitive-Collections#31]
Hello :)

I would like to use this library in some projects at @SIX 
but it is forbidden to use non-maven central repositories. I guess that also other "enterprise" users have the same constraints.

Would it be possible to deploy the library on maven central too?
Thanks!

**Comment by Speiger** [comment]
@dfa1 Yeah I should/will look into that.
When i first started this project this seemed rather complex and jitpack was rather a simple solution.

But it might take a week or two due to me being right now catching up on projects.
I hope that isn't a deal breaker.

**Comment by dfa1** [comment]
@Speiger  hi :) yeah, take your time... there is no immediate urgency!

**Comment by alonhes** [comment]
we are also waiting for this one.
Thanks

**Comment by Speiger** [comment]
Small update.
I haven't had time to work on this yet but i have made the required accounts already, just didn't have the time to read into all documents etc.
Should be done by the end of next week though

**Comment by Speiger** [comment]
@dfa1 @alonhes maven central release is out.
It was painful. And i hated doing every bit of it, but it was worth it. (Jitpack is a lot better IMO)

Sorry for keeping you waiting for so long.
Link: 
https://central.sonatype.com/artifact/io.github.speiger/Primitive-Collections
