### ISSUE TITLE
Better Name suggestion

### ISSUE THREAD

**Issue by Speiger** [Speiger/Primitive-Collections#5]
When I created this Library this was only a "Temporary" name that kinda became final...

I am not perfectly happy with that name but I keeping it until there is a better one found...
Since people will most likely ask if I could rename it:

Throw in suggestions, If I like it I will most likely change to it.

Thanks for reading.

**Comment by tklinchik** [comment]
Keep it simple - speiger-collections and lower case for consistency with many libraries out there.
Also, my suggestion would be to drop "src" from the package name - `speiger.src.collections.longs....` -> `speiger.collections.longs....`

**Comment by Speiger** [comment]
As much as the "Packaging" is egotistic, I personally don't want to put my name into the Library Name.
It was one of the suggestions where I already said no to before this name became the "final placeholder name"

The package name + src part is because of how all my projects are structured.
I will think about removing the src part before the 1.0 release (yes I am leaving myself a lot of time)
@tklinchik thanks for the suggestion though

**Comment by Speiger** [comment]
I think I am going to stay with Primitive Collections, while that might cause some confusion, I don't think that I will come up with a better name.
